color_dict ={
    "question01": {"yellow": 1, "green": 0, "cyan": 1, "red": 1, "gray": 1, "purple": 0, "orange": 0, "magenta": 1, "blue": 0, "pink": 0},
    "question02": {"yellow": 0, "green": 0, "cyan": 0, "red": 0, "gray": 1, "purple": 0, "orange": 0, "magenta": 0, "blue": 0, "pink": 1},
    "question03": {"yellow": 1, "green": 1, "cyan": 0, "red": 0, "gray": 0, "purple": 1, "orange": 1, "magenta": 0, "blue": 0, "pink": 0},
    "question04": {"yellow": 1, "green": 0, "cyan": 0, "red": 0, "gray": 1, "purple": 0, "orange": 0, "magenta": 0, "blue": 0, "pink": 0},
    "question05": {"yellow": 0, "green": 1, "cyan": 1, "red": 0, "gray": 0, "purple": 1, "orange": 0, "magenta": 0, "blue": 0, "pink": 0},
    "question06": {"yellow": 0, "green": 1, "cyan": 0, "red": 0, "gray": 0, "purple": 0, "orange": 1, "magenta": 1, "blue": 0, "pink": 0},
    "question07": {"yellow": 0, "green": 1, "cyan": 0, "red": 0, "gray": 1, "purple": 0, "orange": 0, "magenta": 0, "blue": 0, "pink": 0},
    "question08": {"yellow": 0, "green": 0, "cyan": 0, "red": 1, "gray": 0, "purple": 0, "orange": 0, "magenta": 1, "blue": 0, "pink": 0},
    "question09": {"yellow": 0, "green": 0, "cyan": 0, "red": 1, "gray": 0, "purple": 0, "orange": 0, "magenta": 1, "blue": 0, "pink": 0},
    "question10": {"yellow": 1, "green": 0, "cyan": 0, "red": 0, "gray": 1, "purple": 1, "orange": 0, "magenta": 0, "blue": 0, "pink": 1},
#    "question11": {"yellow": 0, "green": 0, "cyan": 1, "red": 1, "gray": 0, "purple": 0, "orange": 1, "magenta": 0, "blue": 0, "pink": 1},
#    "question12": {"yellow": 0, "green": 0, "cyan": 1, "red": 1, "gray": 0, "purple": 1, "orange": 0, "magenta": 0, "blue": 0, "pink": 1},
#    "question13": {"yellow": 0, "green": 0, "cyan": 1, "red": 1, "gray": 0, "purple": 0, "orange": 0, "magenta": 1, "blue": 0, "pink": 0},
#    "question14": {"yellow": 1, "green": 0, "cyan": 0, "red": 0, "gray": 1, "purple": 0, "orange": 0, "magenta": 0, "blue": 0, "pink": 0},
#    "question15": {"yellow": 1, "green": 0, "cyan": 0, "red": 0, "gray": 1, "purple": 0, "orange": 0, "magenta": 0, "blue": 0, "pink": 0},
#    "question16": {"yellow": 0, "green": 0, "cyan": 1, "red": 1, "gray": 1, "purple": 0, "orange": 0, "magenta": 1, "blue": 0, "pink": 1},
#    "question17": {"yellow": 1, "green": 1, "cyan": 0, "red": 0, "gray": 0, "purple": 0, "orange": 1, "magenta": 1, "blue": 1, "pink": 1},
#    "question18": {"yellow": 0, "green": 0, "cyan": 0, "red": 1, "gray": 0, "purple": 0, "orange": 0, "magenta": 1, "blue": 0, "pink": 0},
#    "question19": {"yellow": 0, "green": 1, "cyan": 0, "red": 0, "gray": 0, "purple": 1, "orange": 0, "magenta": 0, "blue": 0, "pink": 0},
#    "question20": {"yellow": 0, "green": 1, "cyan": 0, "red": 1, "gray": 0, "purple": 0, "orange": 0, "magenta": 1, "blue": 0, "pink": 0},
#    "question21": {"yellow": 0, "green": 0, "cyan": 0, "red": 1, "gray": 0, "purple": 0, "orange": 0, "magenta": 1, "blue": 0, "pink": 0},
#    "question22": {"yellow": 0, "green": 0, "cyan": 0, "red": 1, "gray": 0, "purple": 0, "orange": 0, "magenta": 1, "blue": 1, "pink": 0},
#    "question23": {"yellow": 0, "green": 0, "cyan": 0, "red": 0, "gray": 0, "purple": 0, "orange": 1, "magenta": 0, "blue": 0, "pink": 0},
#    "question24": {"yellow": 0, "green": 0, "cyan": 0, "red": 0, "gray": 0, "purple": 0, "orange": 0, "magenta": 0, "blue": 0, "pink": 1},
#    "question25": {"yellow": 0, "green": 0, "cyan": 1, "red": 1, "gray": 0, "purple": 0, "orange": 0, "magenta": 1, "blue": 1, "pink": 0},
#    "question26": {"yellow": 0, "green": 0, "cyan": 1, "red": 0, "gray": 1, "purple": 0, "orange": 0, "magenta": 0, "blue": 1, "pink": 0},
#    "question27": {"yellow": 0, "green": 0, "cyan": 0, "red": 1, "gray": 1, "purple": 0, "orange": 0, "magenta": 1, "blue": 1, "pink": 0},
#    "question28": {"yellow": 0, "green": 0, "cyan": 1, "red": 0, "gray": 0, "purple": 1, "orange": 0, "magenta": 0, "blue": 1, "pink": 0},
#    "question29": {"yellow": 1, "green": 1, "cyan": 0, "red": 0, "gray": 0, "purple": 0, "orange": 0, "magenta": 1, "blue": 0, "pink": 1},
#    "question30": {"yellow": 0, "green": 1, "cyan": 1, "red": 0, "gray": 1, "purple": 0, "orange": 0, "magenta": 1, "blue": 0, "pink": 0},
#    "question31": {"yellow": 1, "green": 1, "cyan": 0, "red": 1, "gray": 0, "purple": 0, "orange": 0, "magenta": 0, "blue": 0, "pink": 1},
#    "question32": {"yellow": 1, "green": 0, "cyan": 0, "red": 1, "gray": 0, "purple": 0, "orange": 0, "magenta": 1, "blue": 0, "pink": 0},
#    "question33": {"yellow": 0, "green": 0, "cyan": 0, "red": 0, "gray": 0, "purple": 0, "orange": 0, "magenta": 1, "blue": 0, "pink": 0},
#    "question34": {"yellow": 1, "green": 0, "cyan": 0, "red": 0, "gray": 0, "purple": 0, "orange": 0, "magenta": 0, "blue": 1, "pink": 0},
#    "question35": {"yellow": 1, "green": 0, "cyan": 0, "red": 0, "gray": 0, "purple": 0, "orange": 1, "magenta": 0, "blue": 0, "pink": 0},
#    "question36": {"yellow": 1, "green": 1, "cyan": 1, "red": 0, "gray": 0, "purple": 0, "orange": 0, "magenta": 0, "blue": 0, "pink": 0},
#    "question37": {"yellow": 0, "green": 1, "cyan": 1, "red": 0, "gray": 0, "purple": 0, "orange": 0, "magenta": 0, "blue": 0, "pink": 0},
#    "question38": {"yellow": 0, "green": 0, "cyan": 1, "red": 1, "gray": 0, "purple": 0, "orange": 0, "magenta": 0, "blue": 1, "pink": 0},
#    "question39": {"yellow": 0, "green": 0, "cyan": 0, "red": 0, "gray": 1, "purple": 1, "orange": 0, "magenta": 0, "blue": 0, "pink": 1},
#    "question40": {"yellow": 0, "green": 0, "cyan": 1, "red": 0, "gray": 0, "purple": 0, "orange": 0, "magenta": 1, "blue": 0, "pink": 0},
#    "question41": {"yellow": 0, "green": 0, "cyan": 0, "red": 1, "gray": 0, "purple": 0, "orange": 0, "magenta": 1, "blue": 1, "pink": 0},
#    "question42": {"yellow": 1, "green": 1, "cyan": 0, "red": 0, "gray": 1, "purple": 0, "orange": 0, "magenta": 0, "blue": 0, "pink": 0},
#    "question43": {"yellow": 1, "green": 1, "cyan": 0, "red": 0, "gray": 1, "purple": 0, "orange": 1, "magenta": 0, "blue": 0, "pink": 0},
#    "question44": {"yellow": 1, "green": 0, "cyan": 0, "red": 0, "gray": 0, "purple": 0, "orange": 0, "magenta": 0, "blue": 1, "pink": 0},
#    "question45": {"yellow": 1, "green": 0, "cyan": 0, "red": 1, "gray": 0, "purple": 0, "orange": 0, "magenta": 0, "blue": 0, "pink": 0},
#    "question46": {"yellow": 0, "green": 1, "cyan": 0, "red": 1, "gray": 0, "purple": 0, "orange": 0, "magenta": 1, "blue": 0, "pink": 0},
#    "question47": {"yellow": 0, "green": 1, "cyan": 1, "red": 1, "gray": 1, "purple": 0, "orange": 0, "magenta": 1, "blue": 1, "pink": 0},
#    "question48": {"yellow": 0, "green": 1, "cyan": 0, "red": 0, "gray": 0, "purple": 1, "orange": 0, "magenta": 0, "blue": 0, "pink": 0},
    "question49": {"yellow": 0, "green": 0, "cyan": 0, "red": 0, "gray": 0, "purple": 0, "orange": 0, "magenta": 0, "blue": 0, "pink": 1}
}